---
title: "3.0.2 Low input results (DES)"
output:
  html_document:
    fig_width: 6
    fig_height: 4
    df_print: paged
editor_options: 
  chunk_output_type: inline
---

# Low input data

```{r}
library(tximport)
library(tidyverse)
# library(ggfortify)
library(myTAI)
```

# Read low input data (in _Ectocarpus_)

This is the same process as `1.0 Save counts`.

```{r}
Ec_DM <- readr::read_csv("data/Ec_Es_DM_10.csv")
Ec_age <- readr::read_tsv("data/2880_gene_ages.tsv") %>% dplyr::rename(GeneID = `#gene`)
```

```{r, results='hide', warning=FALSE, message=FALSE}
sample_info_ec_full <- 
  readr::read_tsv("metadata_final.tsv") %>% 
  dplyr::filter(Species == "Ec") %>%
  dplyr::mutate(
    N_cell = dplyr::case_when(
      str_detect(Stage, "meiospore|mitospore|gamete") ~ "unicellular",
      TRUE ~ "multicellular"))
  #     Stage, "meiospore|mitospore|gamete" ~ "unicellular",
  #   TRUE ~ "multicellular")
  # )

sample_info_ec <- 
  sample_info_ec_full %>%
  dplyr::filter(
    SeqProt == "Low") %>% 
  dplyr::filter(Experiment == "RAP") %>%
  dplyr::filter(Tissue %in% c("All", "rhizoid")) %>%
  tidyr::unite("stage_tissue", Stage:Tissue, remove = FALSE) %>%
  dplyr::mutate(
    stage_tissue = stringr::str_remove(stage_tissue, '_All')
    ) %>%
  dplyr::arrange(
    base::match(
      Stage, 
      c("meiospore", "earlyGA", "immGA", "matGA", "oldGA", "gamete", "earlyPSP", "immPSP", "matPSP", "mitospore"))
    ) %>%
  dplyr::filter(!SampleName %in% c("F_oldGA_R_1", "F_oldGA_R_2"))


sample_info_ec$Stage <- 
  factor(
    sample_info_ec$Stage, 
    levels = c("meiospore", "earlyGA", "immGA", "matGA", "oldGA", "gamete", "earlyPSP", "immPSP", "matPSP", "mitospore"))

Ec_files <- 
  stringr::str_c(
    "data/Ec_salmon2/", 
    sample_info_ec$LibName, 
    "/quant.sf") %>%
  purrr::set_names(sample_info_ec$SampleName)

Ec_tx2gene <- 
  dplyr::select(Ec_age, GeneID) %>% 
  dplyr::mutate(IsoID = GeneID)
```

```{r}
# use abundance
Ec_txi <- 
  tximport(
    Ec_files, 
    type = "salmon", 
    tx2gene = Ec_tx2gene,
    countsFromAbundance = "lengthScaledTPM")
```

```{r}
Ec_abundance <-
  readr::read_csv("data/Ec_abundance.csv") %>%
  dplyr::select(
    !dplyr::contains("_low_")
  )
# using the same gene set as the total data
Ec_abundance_low <-
  Ec_txi$abundance[Ec_abundance$GeneID, ] %>%
  tibble::as_tibble(rownames = "GeneID")
```

# Plot low input TAI

## Prepare data

```{r}
TDI_process <- function(expression_set, DS_data, transform = "none", pseudocount = 0, integerise = FALSE){
  INPUT <- 
    expression_set
  DES_data <- 
    INPUT %>% 
    dplyr::left_join(
      dplyr::select(DS_data, c("GeneID","DS"))) %>%
    dplyr::relocate(DS) %>%
    tidyr::drop_na()
  if (transform == "rank") {
    DES_data <- myTAI::tf(DES_data, FUN = function(x) apply(x, 2, base::rank))
  } else if (transform != "none") {
    tf_func <- match.fun(transform)
    DES_data <- myTAI::tf(DES_data, FUN = tf_func, pseudocount = pseudocount, integerise = integerise)
  }
  TDI_tibble <-
    DES_data %>%
    myTAI::TDI() %>%
    tibble::as_tibble(rownames = "SampleName") %>%
    dplyr::rename(TDI = value)
  return(TDI_tibble)
}
```

```{r, results='hide', warning=FALSE, message=FALSE}
TDI_bind <- 
  rbind(
    TDI_process(Ec_abundance, Ec_DM),
    TDI_process(Ec_abundance_low, Ec_DM)
  ) %>% 
  left_join(sample_info_ec_full)

TDI_bind.sqrt <- 
  rbind(
    TDI_process(Ec_abundance, Ec_DM, transform = "sqrt"),
    TDI_process(Ec_abundance_low, Ec_DM, transform = "sqrt")
  ) %>% 
  left_join(sample_info_ec_full)

TDI_bind.log2 <- 
  rbind(
    TDI_process(Ec_abundance, Ec_DM, transform = "log2", pseudocount = 1),
    TDI_process(Ec_abundance_low, Ec_DM, transform = "log2", pseudocount = 1)
  ) %>% 
  left_join(sample_info_ec_full)

TDI_bind.rank <- 
  rbind(
    TDI_process(Ec_abundance, Ec_DM, transform = "rank"),
    TDI_process(Ec_abundance_low, Ec_DM, transform = "rank")
  ) %>% 
  left_join(sample_info_ec_full)

library(DESeq2)
TDI_bind.rlog <- 
  rbind(
    TDI_process(Ec_abundance, Ec_DM, transform = "rlog", integerise = TRUE),
    TDI_process(Ec_abundance_low, Ec_DM, transform = "rlog", integerise = TRUE)
  ) %>% 
  left_join(sample_info_ec_full)
```

## Plot

```{r}
TDI_bind %>%
  ggplot2::ggplot(
    aes(x = SeqProt, y = TDI, colour = Stage)
  ) +
  ggplot2::geom_jitter(width = 0.3, size = 4, alpha = 0.5) +
  ggplot2::labs(x = "Sequencing protocol", 
                y = "TDI",
                title = "TDI differs",
                subtitle = "Ectocarpus (TPM)") +
  ggplot2::theme_classic()

TDI_bind.sqrt %>%
  ggplot2::ggplot(
    aes(x = SeqProt, y = TDI, colour = Stage)
  ) +
  ggplot2::geom_jitter(width = 0.3, size = 4, alpha = 0.5) +
  ggplot2::labs(x = "Sequencing protocol", 
                y = "TDI",
                title = "TDI differs",
                subtitle = "Ectocarpus sqrt(TPM)") +
  ggplot2::theme_classic()

TDI_bind.log2 %>%
  ggplot2::ggplot(
    aes(x = SeqProt, y = TDI, colour = Stage)
  ) +
  ggplot2::geom_jitter(width = 0.3, size = 4, alpha = 0.5) +
  ggplot2::labs(x = "Sequencing protocol", 
                y = "TDI",
                title = "TDI differs",
                subtitle = "Ectocarpus log2(TPM+1)") +
  ggplot2::theme_classic()

TDI_bind.rank %>%
  ggplot2::ggplot(
    aes(x = SeqProt, y = TDI, colour = Stage)
  ) +
  ggplot2::geom_jitter(width = 0.3, size = 4, alpha = 0.5) +
  ggplot2::labs(x = "Sequencing protocol", 
                y = "TDI",
                title = "TDI differs",
                subtitle = "Ectocarpus rank(TPM)") +
  ggplot2::theme_classic()

TDI_bind.rlog %>%
  ggplot2::ggplot(
    aes(x = SeqProt, y = TDI, colour = Stage)
  ) +
  ggplot2::geom_jitter(width = 0.3, size = 4, alpha = 0.5) +
  ggplot2::labs(x = "Sequencing protocol", 
                y = "TDI",
                title = "TDI differs",
                subtitle = "Ectocarpus rlog(TPM)") +
  ggplot2::theme_classic()
```

## But unicellular stages tend to be younger

```{r}
TDI_bind %>%
  dplyr::filter(SeqProt == "Low") %>%
  ggplot2::ggplot(
    aes(x = N_cell, y = TDI, colour = Stage, shape = Sex)
  ) +
  ggplot2::geom_jitter(width = 0.3, size = 4, alpha = 0.5) +
  ggplot2::labs(x = "Life cycle phase", 
                y = "TDI",
                title = "Unicellular stages are younger",
                subtitle = "Ectocarpus (TPM)") +
  ggplot2::theme_classic()

TDI_bind.sqrt %>%
  dplyr::filter(SeqProt == "Low") %>%
  ggplot2::ggplot(
    aes(x = N_cell, y = TDI, colour = Stage, shape = Sex)
  ) +
  ggplot2::geom_jitter(width = 0.3, size = 4, alpha = 0.5) +
  ggplot2::labs(x = "Life cycle phase", 
                y = "TDI",
                title = "Unicellular stages are younger",
                subtitle = "Ectocarpus sqrt(TPM)") +
  ggplot2::theme_classic()

TDI_bind.log2 %>%
  dplyr::filter(SeqProt == "Low") %>%
  ggplot2::ggplot(
    aes(x = N_cell, y = TDI, colour = Stage, shape = Sex)
  ) +
  ggplot2::geom_jitter(width = 0.3, size = 4, alpha = 0.5) +
  ggplot2::labs(x = "Life cycle phase", 
                y = "TDI",
                title = "Unicellular stages are younger",
                subtitle = "Ectocarpus log2(TPM+1)") +
  ggplot2::theme_classic()

TDI_bind.rank %>%
  dplyr::filter(SeqProt == "Low") %>%
  ggplot2::ggplot(
    aes(x = N_cell, y = TDI, colour = Stage, shape = Sex)
  ) +
  ggplot2::geom_jitter(width = 0.3, size = 4, alpha = 0.5) +
  ggplot2::labs(x = "Life cycle phase", 
                y = "TDI",
                title = "Unicellular stages are younger",
                subtitle = "Ectocarpus rank(TPM)") +
  ggplot2::theme_classic()

TDI_bind.rlog %>%
  dplyr::filter(SeqProt == "Low") %>%
  ggplot2::ggplot(
    aes(x = N_cell, y = TDI, colour = Stage, shape = Sex)
  ) +
  ggplot2::geom_jitter(width = 0.3, size = 4, alpha = 0.5) +
  ggplot2::labs(x = "Life cycle phase", 
                y = "TDI",
                title = "Unicellular stages are younger",
                subtitle = "Ectocarpus rlog(TPM)") +
  ggplot2::theme_classic()
```

# TDI profile

```{r}
construct_DES <- 
  function(
    ExpressionMatrix, 
    GeneAgeTable, 
    metadata, 
    AVG = median,
    grouping_var = "Stage",
    name_var = "LibName",
    transform_opt = F,
    transformation){
  RepCol <- 
    metadata %>% 
    dplyr::group_by(.data[[grouping_var]]) %>% 
    dplyr::summarize(n=dplyr::n()) %>% 
    dplyr::arrange(
      base::factor(
        .data[[grouping_var]], 
        levels = base::unique(metadata[,grouping_var][[1]])
        )
      ) %>% 
    base::as.vector()
  # making sure the metadata and the expression set match
  DES <- 
    ExpressionMatrix %>%
    dplyr::left_join(
      dplyr::select(
        GeneAgeTable, 
        c(GeneID, DS)
        )
      ) %>%
    tidyr::drop_na() %>% # NAs can ruin the transformation.
    dplyr::relocate(DS, GeneID) 
  if(transform_opt){
    if(transformation == "rlog"){
      DES <-
        myTAI::tf(
          DES,
          FUN = rlog,
          integerise = TRUE)
    }
    else if(transformation == "vst"){
      DES <-
        myTAI::tf(
          DES,
          FUN = vst,
          integerise = TRUE)
    }
  }
  # return(RepCol)
  DES_FILT <- 
    DES %>%
    dplyr::select(1:2 | metadata[,name_var][[1]])
  # return(DES_FILT)
  OUT <- DES_FILT %>%
    myTAI::CollapseReplicates(
      RepCol$n,
      AVG, 
      stage.names = base::as.character(RepCol[[grouping_var]]))
  return(OUT)
}

```

```{r}
Ec_abundance_25f_low <-
  Ec_abundance_low %>%
  dplyr::select(1 | dplyr::starts_with("F_"))
Ec_abundance_32m_low <-
  Ec_abundance_low %>%
  dplyr::select(1 | dplyr::starts_with("M_"))

# Ec_DES_25f_low <- 
Ec_DES_25f_low <-
  construct_DES(
    Ec_abundance_25f_low, 
    Ec_DM, 
    dplyr::filter(
      sample_info_ec, 
      Sex == "F"),
    name_var = "SampleName"
    )
# I took some time to realise I had to add as.character() to myTAI::CollapseReplicates()

Ec_DES_32m_low <- 
  construct_DES(
    Ec_abundance_32m_low, 
    Ec_DM, 
    dplyr::filter(
      sample_info_ec, 
      Sex == "M"),
    name_var = "SampleName"
    )

# rlog transforms
Ec_DES_25f_low.rlog <- 
  construct_DES(
    Ec_abundance_25f_low, 
    Ec_DM, 
    dplyr::filter(
      sample_info_ec, 
      Sex == "F"),
    name_var = "SampleName",
    transform_opt = TRUE,
    transformation = "rlog"
    )
Ec_DES_32m_low.rlog <- 
  construct_DES(
    Ec_abundance_32m_low, 
    Ec_DM, 
    dplyr::filter(
      sample_info_ec, 
      Sex == "M"),
    name_var = "SampleName",
    transform_opt = TRUE,
    transformation = "rlog"
    )

```


```{r}
#TI stands for transcriptome index
TI.preplot <- function(ExpressionSet, permutations = 50000, ordered_stages){
  std <- 
    myTAI::bootMatrix(
      ExpressionSet = ExpressionSet, 
      permutations  = permutations) %>% 
    apply(2, stats::sd)
  TI.out <- 
    myTAI::TDI(ExpressionSet) %>%
    tibble::as_tibble(rownames = "Stage", colnames = c("TDI", "DS")) %>% 
    dplyr::bind_cols(as_tibble(std)) %>%
    dplyr::rename(TDI = 2, sd = 3)
  return(TI.out)
}
```

```{r}
Ec_TDI_25f_low <-
  TI.preplot(Ec_DES_25f_low) %>%
  dplyr::mutate(Sex = "F")
Ec_TDI_25f_low.sqrt <-
  TI.preplot(myTAI::tf(Ec_DES_25f_low, FUN = sqrt)) %>%
  dplyr::mutate(Sex = "F")
Ec_TDI_25f_low.log2 <-
  TI.preplot(myTAI::tf(Ec_DES_25f_low, FUN = log2, pseudocount = 1)) %>%
  dplyr::mutate(Sex = "F")
Ec_TDI_25f_low.rank <-
  TI.preplot(myTAI::tf(Ec_DES_25f_low, FUN = function(x) apply(x, 2, base::rank))) %>%
  dplyr::mutate(Sex = "F")
Ec_TDI_25f_low.rlog <-
  TI.preplot(Ec_DES_25f_low.rlog) %>%
  dplyr::mutate(Sex = "F")

Ec_TDI_32m_low <-
  TI.preplot(Ec_DES_32m_low) %>%
  dplyr::mutate(Sex = "M")
Ec_TDI_32m_low.sqrt <-
  TI.preplot(myTAI::tf(Ec_DES_32m_low, FUN = sqrt)) %>%
  dplyr::mutate(Sex = "M")
Ec_TDI_32m_low.log2 <-
  TI.preplot(myTAI::tf(Ec_DES_32m_low, FUN = log2, pseudocount = 1)) %>%
  dplyr::mutate(Sex = "M")
Ec_TDI_32m_low.rank <-
  TI.preplot(myTAI::tf(Ec_DES_32m_low, FUN = function(x) apply(x, 2, base::rank))) %>%
  dplyr::mutate(Sex = "M")
Ec_TDI_32m_low.rlog <-
  TI.preplot(Ec_DES_32m_low.rlog) %>%
  dplyr::mutate(Sex = "M")
```

```{r}
stage_order <- 
  function(female, male, metadata){
    data_bind <-  
      rbind(male, female)
    data_bind$Stage <-
      base::factor(
        data_bind$Stage,
        levels(metadata$Stage)
      )
    return(data_bind)
  }
```
```{r}
# TDI_bind2_ordered <- 
#   rbind(Ec_TDI_25f_low, Ec_TDI_32m_low)
# TDI_bind2_ordered$Stage <- 
#   base::factor(
#     TDI_bind2_ordered$Stage, 
#     levels(sample_info_ec$Stage))

stage_order(Ec_TDI_25f_low, Ec_TDI_32m_low, sample_info_ec) %>%
  ggplot2::ggplot(
    aes(
      y = TDI, 
      x = Stage,
      group = Sex,
      colour = Sex,
      fill = Sex)) +
  ggplot2::geom_errorbar(
    aes(ymin = TDI - sd,
        ymax = TDI + sd
        ), 
    width = 0.3, size = 2, alpha = 0.5) +
  ggplot2::geom_point(size = 3) +
  theme_classic() +
  ggsci::scale_colour_npg() +
  labs(title = "Ectocarpus (low input; 50000 permutations)",
       subtitle = "TPM")

stage_order(Ec_TDI_25f_low.sqrt, Ec_TDI_32m_low.sqrt, sample_info_ec) %>%
  ggplot2::ggplot(
    aes(
      y = TDI, 
      x = Stage,
      group = Sex,
      colour = Sex,
      fill = Sex)) +
  ggplot2::geom_errorbar(
    aes(ymin = TDI - sd,
        ymax = TDI + sd
        ),
    width = 0.3, size = 2, alpha = 0.5) +
  ggplot2::geom_point(size = 3) +
  theme_classic() +
  ggsci::scale_colour_npg() +
  labs(title = "Ectocarpus (low input; 50000 permutations)",
       subtitle = "sqrt(TPM)")

stage_order(Ec_TDI_25f_low.log2, Ec_TDI_32m_low.log2, sample_info_ec) %>%
  ggplot2::ggplot(
    aes(
      y = TDI, 
      x = Stage,
      group = Sex,
      colour = Sex,
      fill = Sex)) +
  ggplot2::geom_errorbar(
    aes(ymin = TDI - sd,
        ymax = TDI + sd
        ), 
    width = 0.3, size = 2, alpha = 0.5) +
  ggplot2::geom_point(size = 3) +
  theme_classic() +
  ggsci::scale_colour_npg() +
  labs(title = "Ectocarpus (low input; 50000 permutations)",
       subtitle = "log2(TPM+1)")

stage_order(Ec_TDI_25f_low.rank, Ec_TDI_32m_low.rank, sample_info_ec) %>%
  ggplot2::ggplot(
    aes(
      y = TDI, 
      x = Stage,
      group = Sex,
      colour = Sex,
      fill = Sex)) +
  ggplot2::geom_errorbar(
    aes(ymin = TDI - sd,
        ymax = TDI + sd
        ),
    width = 0.3, size = 2, alpha = 0.5) +
  ggplot2::geom_point(size = 3) +
  theme_classic() +
  ggsci::scale_colour_npg() +
  labs(title = "Ectocarpus (low input; 50000 permutations)",
       subtitle = "rank(TPM)")

stage_order(Ec_TDI_25f_low.rlog, Ec_TDI_32m_low.rlog, sample_info_ec) %>%
  ggplot2::ggplot(
    aes(
      y = TDI, 
      x = Stage,
      group = Sex,
      colour = Sex,
      fill = Sex)) +
  ggplot2::geom_errorbar(
    aes(ymin = TDI - sd,
        ymax = TDI + sd
        ),
    width = 0.3, size = 2, alpha = 0.5) +
  ggplot2::geom_point(size = 3) +
  theme_classic() +
  ggsci::scale_colour_npg() +
  labs(title = "Ectocarpus (low input; 50000 permutations)",
       subtitle = "rlog(TPM)")
```

Get session info.

```{r}
devtools::session_info()
```