---
title: "Orthogroup analysis msc"
output:
  html_document:
    fig_width: 5
    fig_height: 4
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: inline
---

# Motivation

Upset plot of orthogroups, as done in [Cossard et al. 2022 Nat Ecol Evol](https://www.nature.com/articles/s41559-022-01692-4) Extended Data Fig. 1.

Load the libraries

```{r, results='hide', warning=FALSE, message=FALSE}
library(topGO)
# library(tximport)
library(corrplot)
library(myTAI)
library(ComplexHeatmap)
source("functions/parse_orthogroups.R")
library(tidyverse)
```

```{r, results='hide', warning=FALSE, message=FALSE}
createGOdata <- function(geneList, ontology, gene2GO_map, nodeSize){
  OUT <- new("topGOdata", 
             description = paste("GOtest", ontology, sep = "_"), 
             ontology = ontology, 
             allGenes = geneList,  
             annot = annFUN.gene2GO, 
             gene2GO = gene_to_go_mapping[-1], 
             nodeSize = nodeSize)
  return(OUT)
}

resultGO <- function(GOdata, algorithm, firstSigNodes = 5, sig = F, plot = F){
  ## Calculate fisher exact test
  result_fisher <- runTest(object    = GOdata,
                           algorithm = algorithm,
                           statistic = "fisher")
  OUT <- GenTable(object  = GOdata,
                  fisher = result_fisher,
                  topNodes = length(score(result_fisher)))
  
  ## Combine results from statistical tests:
  
  ## Correct for multiple testing:
  OUT$fisher <- as.numeric(OUT$fisher)
  OUT$fisher_adjusted <- p.adjust(p = OUT$fisher, method = c("fdr"))
  if(sig == F & plot == F){
    return(OUT)
  }
  ## Subset calls with significance higher than expected:
  if(plot == F){
    OUT_sig <- subset(x = OUT,
                      subset = (Significant > Expected) & (fisher_adjusted < 0.1))
    return(OUT_sig)
  }
  plot_OUT <- showSigOfNodes(GOdata, score(result_fisher),
                             firstSigNodes = firstSigNodes,
                             useInfo ='all')
  return(plot_OUT)
}
```

```{r, message=FALSE, warning=FALSE}
Fs_ddsObj.wald_nonDEGlist <-
  base::readRDS("data/Fs_wald_nonDEG_list.rds")
Fd_ddsObj.wald_nonDEGlist <-
  base::readRDS("data/Fd_wald_nonDEG_list.rds")
```

```{r, message=FALSE, warning=FALSE}
resnonDEG_24H48H <- Fs_ddsObj.wald_nonDEGlist[[1]] %>% 
        tibble::as_tibble(rownames = "GeneID") %>% 
        dplyr::mutate(stage = "24H_to_48H") %>% 
        dplyr::mutate(test = "nonDEG") %>%
        dplyr::mutate(species = "Fs")
resnonDEG_48H1w <- Fs_ddsObj.wald_nonDEGlist[[2]] %>% 
        tibble::as_tibble(rownames = "GeneID") %>% 
        dplyr::mutate(stage = "48H_to_1w") %>%  
        dplyr::mutate(test = "nonDEG") %>% 
        dplyr::mutate(species = "Fs")
resnonDEG_1w3w <- Fs_ddsObj.wald_nonDEGlist[[3]] %>% 
        tibble::as_tibble(rownames = "GeneID") %>% 
        dplyr::mutate(stage = "1w_to_3w") %>% 
        dplyr::mutate(test = "nonDEG") %>%
        dplyr::mutate(species = "Fs")
resnonDEG_3w4w <- Fs_ddsObj.wald_nonDEGlist[[4]] %>% 
        tibble::as_tibble(rownames = "GeneID") %>% 
        dplyr::mutate(stage = "3w_to_4w") %>% 
        dplyr::mutate(test = "nonDEG") %>%
        dplyr::mutate(species = "Fs")

resnonDEG_24H48H_Fd <- Fd_ddsObj.wald_nonDEGlist[[1]] %>% 
        tibble::as_tibble(rownames = "GeneID") %>% 
        dplyr::mutate(stage = "1E_to_2E") %>% 
        dplyr::mutate(test = "nonDEG") %>%
        dplyr::mutate(species = "Fd")
resnonDEG_48H1w_Fd <- Fd_ddsObj.wald_nonDEGlist[[2]] %>% 
        tibble::as_tibble(rownames = "GeneID") %>% 
        dplyr::mutate(stage = "2E_to_3E") %>% 
        dplyr::mutate(test = "nonDEG") %>%
        dplyr::mutate(species = "Fd")
resnonDEG_1w3w_Fd <- Fd_ddsObj.wald_nonDEGlist[[3]] %>% 
        tibble::as_tibble(rownames = "GeneID") %>% 
        dplyr::mutate(stage = "3E_to_4E") %>% 
        dplyr::mutate(test = "nonDEG") %>%
        dplyr::mutate(species = "Fd")
resnonDEG_3w4w_Fd <- Fd_ddsObj.wald_nonDEGlist[[4]] %>% 
        tibble::as_tibble(rownames = "GeneID") %>% 
        dplyr::mutate(stage = "4E_to_5E") %>% 
        dplyr::mutate(test = "nonDEG") %>%
        dplyr::mutate(species = "Fd")

# resDEG_24H48H <- read_csv("GO_input/resDEG_24H48H_Fs.csv", show_col_types = FALSE) %>% 
#   mutate(stage = "24H_to_48H") %>% 
#   mutate(test = "DEG") %>%
#   mutate(species = "Fs")
# resDEG_48H1w <- read_csv("GO_input/resDEG_48H1w_Fs.csv", show_col_types = FALSE) %>% 
#   mutate(stage = "48H_to_1w") %>% 
#   mutate(test = "DEG") %>%
#   mutate(species = "Fs")
# resDEG_1w3w <- read_csv("GO_input/resDEG_1w3w_Fs.csv", show_col_types = FALSE) %>% 
#   mutate(stage = "1w_to_3w") %>% 
#   mutate(test = "DEG") %>%
#   mutate(species = "Fs")
# resDEG_3w4w <- read_csv("GO_input/resDEG_3w4w_Fs.csv", show_col_types = FALSE) %>% 
#   mutate(stage = "3w_to_4w") %>% 
#   mutate(test = "DEG") %>%
#   mutate(species = "Fs")

# resDEG_24H48H_Fd <- read_csv("GO_input/resDEG_24H48H_Fd.csv", show_col_types = FALSE) %>% 
#   mutate(stage = "1E_to_2E") %>% 
#   mutate(test = "DEG") %>%
#   mutate(species = "Fd")
# resDEG_48H1w_Fd <- read_csv("GO_input/resDEG_48H1w_Fd.csv", show_col_types = FALSE) %>% 
#   mutate(stage = "2E_to_3E") %>% 
#   mutate(test = "DEG") %>%
#   mutate(species = "Fd")
# resDEG_1w3w_Fd <- read_csv("GO_input/resDEG_1w3w_Fd.csv", show_col_types = FALSE) %>% 
#   mutate(stage = "3E_to_4E") %>% 
#   mutate(test = "DEG") %>%
#   mutate(species = "Fd")
# resDEG_3w4w_Fd <- read_csv("GO_input/resDEG_3w4w_Fd.csv", show_col_types = FALSE) %>% 
#   mutate(stage = "4E_to_5E") %>% 
#   mutate(test = "DEG") %>%
#   mutate(species = "Fd")
```

```{r}
combined_table <- rbind(resnonDEG_24H48H, resnonDEG_48H1w, resnonDEG_1w3w, resnonDEG_3w4w,
                        resnonDEG_24H48H_Fd, resnonDEG_48H1w_Fd, resnonDEG_1w3w_Fd, resnonDEG_3w4w_Fd)
                        # resDEG_24H48H, resDEG_48H1w, resDEG_1w3w, resDEG_3w4w
                        # resDEG_24H48H_Fd, resDEG_48H1w_Fd, resDEG_1w3w_Fd, resDEG_3w4w_Fd
```

```{r}
make_list_UpSet <- function(INPUT_table, padj_threshold = 0.1, DEG_type, species_name, make_list = T){
  FILTER_INPUT <- INPUT_table %>% 
    dplyr::filter(padj < padj_threshold) %>%
    dplyr::filter(test == DEG_type) %>%
    dplyr::filter(species == species_name) %>%
    dplyr::select(GeneID, stage)
  if(make_list == F) {
    return(FILTER_INPUT)
  }
  OUT <- utils::unstack(FILTER_INPUT, GeneID ~ stage)
  return(OUT)
}
```


```{r, message=FALSE, warning=FALSE}
GeneList <- make_list_UpSet(combined_table, padj_threshold = 0.1, DEG_type = "nonDEG", species_name = "Fs")
upsetting_input_distinct <- ComplexHeatmap::make_comb_mat(GeneList, mode = "distinct")
ComplexHeatmap::UpSet(upsetting_input_distinct,
                      set_order = c(2,4,1,3),
                      row_title = "Stage transitions")
```

```{r, message=FALSE, warning=FALSE}
GO_GeneList_Fs <- make_list_UpSet(combined_table, padj_threshold = 0.1, DEG_type = "nonDEG", species_name = "Fs", make_list = F) %>%
  dplyr::mutate(seen = 1) %>%
  pivot_wider(names_from = stage, values_from = seen) %>%
  drop_na() %>% 
  dplyr::select(GeneID)
```

We keep 2630 out of 6492 genes.

```{r, message=FALSE, warning=FALSE}
GeneList <- make_list_UpSet(combined_table, padj_threshold = 0.1, DEG_type = "nonDEG", species_name = "Fd")
upsetting_input_distinct <- ComplexHeatmap::make_comb_mat(GeneList, mode = "distinct")
ComplexHeatmap::UpSet(upsetting_input_distinct,
                      set_order = c(1,2,3,4),
                      row_title = "Stage transitions")
```

```{r, message=FALSE, warning=FALSE}
GO_GeneList_Fd <- make_list_UpSet(combined_table, padj_threshold = 0.1, DEG_type = "nonDEG", species_name = "Fd", make_list = F) %>%
  dplyr::mutate(seen = 1) %>%
  pivot_wider(names_from = stage, values_from = seen) %>%
  drop_na() %>% 
  dplyr::select(GeneID)
```

```{r}
GO_GeneList_Fs
GO_GeneList_Fd
```

```{r, message=FALSE, warning=FALSE}
gene_to_go_mapping <- readMappings(file = "GO_input/temp_GOmap_Fs.csv", sep = ",", IDsep = "\\|")
GO_background <- combined_table %>% 
  dplyr::filter(species == "Fs") %>%
  dplyr::select(GeneID) %>% 
  unique()
GO_query <- GO_GeneList_Fs

geneList <- factor(as.integer(GO_background$GeneID %in% GO_query$GeneID))
names(geneList) <- GO_background$GeneID
# "parentchild" can also be used as algorithm.
myGOdata_CC <- createGOdata(geneList, ontology = "CC", 
                            gene2GO_map = gene_to_go_mapping[-1], nodeSize = 10)
myGOdata_BP <- createGOdata(geneList, ontology = "BP", 
                            gene2GO_map = gene_to_go_mapping[-1], nodeSize = 10)
myGOdata_MF <- createGOdata(geneList, ontology = "MF", 
                            gene2GO_map = gene_to_go_mapping[-1], nodeSize = 10)

resGO_CC <- resultGO(myGOdata_CC, "parentchild")
resGO_BP <- resultGO(myGOdata_BP, "parentchild")
resGO_MF <- resultGO(myGOdata_MF, "parentchild")
```

```{r}
resGO_CC %>% 
  dplyr::filter(fisher_adjusted < 0.1) %>%
  dplyr::select(GO.ID, Term, Significant, Expected, fisher)
resGO_BP %>% 
  dplyr::filter(fisher_adjusted < 0.1) %>%
  dplyr::select(GO.ID, Term, Significant, Expected, fisher)
resGO_MF %>% 
  dplyr::filter(fisher_adjusted < 0.1) %>%
  dplyr::select(GO.ID, Term, Significant, Expected, fisher)
```

```{r, message=FALSE, warning=FALSE}
gene_to_go_mapping <- readMappings(file = "GO_input/temp_GOmap_Fd.csv", sep = ",", IDsep = "\\|")
GO_background <- combined_table %>% 
  dplyr::filter(species == "Fd") %>%
  dplyr::select(GeneID) %>% 
  unique()
GO_query <- GO_GeneList_Fd

geneList <- factor(as.integer(GO_background$GeneID %in% GO_query$GeneID))
names(geneList) <- GO_background$GeneID
# "parentchild" can also be used as algorithm.
myGOdata_CC <- createGOdata(geneList, ontology = "CC", 
                            gene2GO_map = gene_to_go_mapping[-1], nodeSize = 10)
myGOdata_BP <- createGOdata(geneList, ontology = "BP", 
                            gene2GO_map = gene_to_go_mapping[-1], nodeSize = 10)
myGOdata_MF <- createGOdata(geneList, ontology = "MF", 
                            gene2GO_map = gene_to_go_mapping[-1], nodeSize = 10)

resGO_CC <- resultGO(myGOdata_CC, "parentchild")
resGO_BP <- resultGO(myGOdata_BP, "parentchild")
resGO_MF <- resultGO(myGOdata_MF, "parentchild")
```

```{r}
resGO_CC %>% 
  dplyr::filter(fisher_adjusted < 0.1) %>%
  dplyr::select(GO.ID, Term, Significant, Expected, fisher)
resGO_BP %>% 
  dplyr::filter(fisher_adjusted < 0.1) %>%
  dplyr::select(GO.ID, Term, Significant, Expected, fisher)
resGO_MF %>% 
  dplyr::filter(fisher_adjusted < 0.1) %>%
  dplyr::select(GO.ID, Term, Significant, Expected, fisher)
```

How does this compare with age?


```{r}
fisherPS <- function(PS_query, PS_nonquery, alternative = "two.sided"){
  INPUT_1 <- PS_query %>% mutate(query = T)
  INPUT_2 <- PS_nonquery %>% mutate(query = F)
  TEST <- rbind(INPUT_1, INPUT_2) %>%
    dplyr::group_by(rank, query) %>%
    summarise(n = n())
  RESULTS <- list()
  for (i in unique(TEST$rank)) {
    sub_df <- TEST[TEST$rank == i, ]
    # create a 2x2 contingency table
    # extract the contingency table
    A <- sum(sub_df$n[sub_df$query == TRUE])
    B <- sum(sub_df$n[sub_df$query == FALSE])
    C <- sum(TEST$n[TEST$query == TRUE]) - A
    D <- sum(TEST$n[TEST$query == FALSE]) - B
    cont_table <- matrix(c(A, B, C, D), nrow = 2, ncol = 2)
    # perform Fisher's exact test
    fisher_test <- fisher.test(cont_table, alternative = alternative)
    
    # store the results
    RESULTS[[i]] <- list(rank = i,
                         odds_ratio = fisher_test$estimate,
                         p_value = fisher_test$p.value,
                         query_prop = A/(B+A),
                         background_prop = C/(D+C))
  }
  # combine the results into a data frame
  OUT <- do.call(rbind.data.frame, RESULTS)
  adjusted_p_values <- p.adjust(OUT$p_value, method = "BH")
  OUT$adjusted_p_value <- adjusted_p_values
  return(OUT)
}
```

```{r}
# Fs_age <- readr::read_csv("data/Fs_age_processed.csv")
# Fd_age <- readr::read_csv("data/Fd_age_processed.csv")
```

```{r}
# PS_query <- GO_GeneList_Fs %>% left_join(Fs_age) %>% dplyr::select(GeneID, rank)
# PS_background <- combined_table %>% dplyr::filter(species == "Fs") %>% dplyr::select(GeneID) %>% unique() %>% left_join(Fs_age) %>% dplyr::select(GeneID, rank)
# 
# PS_nonquery <- subset(PS_background, !GeneID %in% PS_query$GeneID)
# 
# mean(PS_query$rank)
# mean(PS_nonquery$rank)
# wilcox.test(PS_query$rank, PS_nonquery$rank, alternative = "greater")
# fisherPS(PS_query, PS_nonquery, alternative = "greater")
# fisherPS(PS_query, PS_nonquery, alternative = "less")
# 
# # double check
# sum(PS_query$rank == 7) / nrow(PS_query)
# sum(PS_nonquery$rank == 7) / nrow(PS_nonquery)
# ```
# 
# ```{r}
# PS_query <- GO_GeneList_Fd %>% left_join(Fd_age) %>% dplyr::select(GeneID, rank)
# PS_background <- combined_table %>% dplyr::filter(species == "Fd") %>% dplyr::select(GeneID) %>% unique() %>% left_join(Fd_age) %>% dplyr::select(GeneID, rank)
# 
# PS_nonquery <- subset(PS_background, !GeneID %in% PS_query$GeneID)
# 
# mean(PS_query$rank)
# mean(PS_nonquery$rank)
# wilcox.test(PS_query$rank, PS_nonquery$rank, alternative = "greater")
# fisherPS(PS_query, PS_nonquery, alternative = "greater")
# fisherPS(PS_query, PS_nonquery, alternative = "less")
# 
# # double check
# sum(PS_query$rank == 7) / nrow(PS_query)
# sum(PS_nonquery$rank == 7) / nrow(PS_nonquery)
```

In both species, PS7 is significantly down regulated in the nonDEGs.